import { AgeGroup, Difficulty } from "./types";

export interface Paragraph {
  id: string;
  group: AgeGroup;
  level: Difficulty;
  title: string;
  kind: "story" | "poem" | "communication";
  text: string;
}

export const PARAGRAPHS: Paragraph[] = [
  // ─────────── PRE-SCHOOL · EASY ───────────
  {
    id: "ps-e-1",
    group: "preschool",
    level: "easy",
    title: "The Little Cat",
    kind: "poem",
    text: "I see a cat. The cat is big. The cat sits on a mat. I like the cat.",
  },
  {
    id: "ps-e-2",
    group: "preschool",
    level: "easy",
    title: "My Dog Max",
    kind: "story",
    text: "I have a dog. My dog is Max. Max can run. Max can jump. Max is my best friend.",
  },
  {
    id: "ps-e-3",
    group: "preschool",
    level: "easy",
    title: "The Sun",
    kind: "poem",
    text: "The sun is up. The sky is blue. The sun is warm. I can see the sun. The sun is nice.",
  },
  {
    id: "ps-e-4",
    group: "preschool",
    level: "easy",
    title: "Red Apple",
    kind: "story",
    text: "I have an apple. My apple is red. The apple is sweet. I share my apple. I love apples.",
  },
  {
    id: "ps-e-5",
    group: "preschool",
    level: "easy",
    title: "Play Time",
    kind: "poem",
    text: "I can run. I can hop. I can skip. I can clap. Play time is so much fun.",
  },

  // ─────────── PRE-SCHOOL · MEDIUM ───────────
  {
    id: "ps-m-1",
    group: "preschool",
    level: "medium",
    title: "My Red Ball",
    kind: "story",
    text: "I have a red ball. I play with my ball every day. My ball jumps high. My ball rolls far. I love my red ball.",
  },
  {
    id: "ps-m-2",
    group: "preschool",
    level: "medium",
    title: "At the Park",
    kind: "story",
    text: "I go to the park with mom. I see many birds on the trees. I play on the slide and swings. The grass is green and soft. I love the park.",
  },
  {
    id: "ps-m-3",
    group: "preschool",
    level: "medium",
    title: "Bath Time",
    kind: "story",
    text: "It is time for my bath. The water is warm and clean. I splash and play with my duck. Mom helps me wash my hair. Now I am fresh and happy.",
  },
  {
    id: "ps-m-4",
    group: "preschool",
    level: "medium",
    title: "The Kind Cow",
    kind: "poem",
    text: "The cow says moo moo. The cow is big and kind. The cow gives us good milk. We drink milk every day. Thank you, dear cow.",
  },
  {
    id: "ps-m-5",
    group: "preschool",
    level: "medium",
    title: "My Toy Car",
    kind: "story",
    text: "I have a small toy car. My car is blue and shiny. I push my car very fast. My car goes around the house. I love my little car.",
  },

  // ─────────── PRE-SCHOOL · HARD ───────────
  {
    id: "ps-h-1",
    group: "preschool",
    level: "hard",
    title: "Twinkle Little Star",
    kind: "poem",
    text: "Twinkle twinkle little star. How I wonder what you are. Up above the world so high. Like a diamond in the sky.",
  },
  {
    id: "ps-h-2",
    group: "preschool",
    level: "hard",
    title: "Jack and Jill",
    kind: "poem",
    text: "Jack and Jill went up the hill to fetch a pail of water. Jack fell down and broke his crown. Jill came tumbling after.",
  },
  {
    id: "ps-h-3",
    group: "preschool",
    level: "hard",
    title: "Humpty Dumpty",
    kind: "poem",
    text: "Humpty Dumpty sat on a wall. Humpty Dumpty had a great fall. All the king's horses and all the king's men could not put him back again.",
  },
  {
    id: "ps-h-4",
    group: "preschool",
    level: "hard",
    title: "Rain Rain Go Away",
    kind: "poem",
    text: "Rain rain go away. Come again another day. Little Johnny wants to play. Rain rain go away.",
  },
  {
    id: "ps-h-5",
    group: "preschool",
    level: "hard",
    title: "Old MacDonald",
    kind: "poem",
    text: "Old MacDonald had a farm. On his farm he had a cow. With a moo moo here and a moo moo there. Here a moo there a moo everywhere a moo moo.",
  },

  // ─────────── SCHOOL · EASY ───────────
  {
    id: "sc-e-1",
    group: "school",
    level: "easy",
    title: "The Kind Rabbit",
    kind: "story",
    text: "A small rabbit lived near a quiet pond. Every morning it shared carrots with its friends. The other animals loved the rabbit for its kindness and its helpful nature.",
  },
  {
    id: "sc-e-2",
    group: "school",
    level: "easy",
    title: "The Hungry Fox",
    kind: "story",
    text: "A fox was walking through a forest when he saw a bunch of grapes hanging from a vine. The grapes looked juicy and sweet. The fox jumped as high as he could, but the grapes were too far. He walked away saying the grapes were probably sour anyway.",
  },
  {
    id: "sc-e-3",
    group: "school",
    level: "easy",
    title: "The Lost Puppy",
    kind: "story",
    text: "A little puppy got lost near the market. A kind girl found him sitting under a tree. She gave him water and took him home. She put up posters all around the neighborhood. Soon the puppy's family came to take him back.",
  },
  {
    id: "sc-e-4",
    group: "school",
    level: "easy",
    title: "The Farmer and His Seeds",
    kind: "story",
    text: "A farmer planted a row of seeds one morning. He watered them every day without fail. Soon tiny green shoots began to appear. The farmer was very happy to see his garden grow. He took good care of each plant until they became strong.",
  },
  {
    id: "sc-e-5",
    group: "school",
    level: "easy",
    title: "A Day at the Beach",
    kind: "story",
    text: "We went to the beach on a sunny Sunday. The sand was warm under our feet. We built a big castle with a tall tower. The waves washed it away, but we only laughed. It was one of the best days ever.",
  },

  // ─────────── SCHOOL · MEDIUM ───────────
  {
    id: "sc-m-1",
    group: "school",
    level: "medium",
    title: "The Clever Crow",
    kind: "story",
    text: "A thirsty crow found a narrow pot with only a little water at the bottom. The crow picked up small stones and dropped them inside the pot. Slowly the water level rose, and the crow happily drank every drop.",
  },
  {
    id: "sc-m-2",
    group: "school",
    level: "medium",
    title: "The Boy Who Cried Wolf",
    kind: "story",
    text: "A shepherd boy thought it would be fun to fool the villagers. He cried out that a wolf was attacking his sheep. The villagers came running, but there was no wolf. When a real wolf appeared the next week, nobody believed him. The boy learned that liars are not trusted even when they tell the truth.",
  },
  {
    id: "sc-m-3",
    group: "school",
    level: "medium",
    title: "The Golden Touch",
    kind: "story",
    text: "Once there was a king who loved gold above all else. A kind spirit granted him a wish, and he asked that everything he touched turn to gold. At first he was delighted, but soon he could not eat his food or hug his daughter. He begged the spirit to take the gift away. From that day forward, he valued family far more than gold.",
  },
  {
    id: "sc-m-4",
    group: "school",
    level: "medium",
    title: "The Ant and the Grasshopper",
    kind: "story",
    text: "During the warm summer days, an ant worked hard storing food for winter. A grasshopper sang and danced, making fun of the ant. When winter arrived, snow covered the ground and the grasshopper had nothing to eat. The ant kindly shared a little food and taught him an important lesson. Hard work today prepares you for tomorrow.",
  },
  {
    id: "sc-m-5",
    group: "school",
    level: "medium",
    title: "The Magic Paintbrush",
    kind: "story",
    text: "A poor boy found a paintbrush that could bring paintings to life. He painted food for the hungry and clothes for the cold. A greedy ruler demanded that he paint mountains of gold. Instead, the boy painted a stormy sea that swallowed the ruler's ship. The magic brush stayed with those who used it to help others.",
  },

  // ─────────── SCHOOL · HARD ───────────
  {
    id: "sc-h-1",
    group: "school",
    level: "hard",
    title: "Morning in the Village",
    kind: "story",
    text: "As the first rays of sunlight crept over the distant hills, the village began to stir. Farmers walked briskly toward their fields while children laughed on their way to school. The fresh breeze carried the sweet scent of jasmine, promising a beautiful day ahead for everyone.",
  },
  {
    id: "sc-h-2",
    group: "school",
    level: "hard",
    title: "The River's Journey",
    kind: "story",
    text: "High in the mountains a small stream begins its long journey to the sea. It collects raindrops and melting snow as it tumbles down rocky cliffs. Along the way it passes through quiet forests, noisy towns, and golden fields of wheat. Fish swim in its waters and birds drink along its banks. By the time it reaches the ocean, it has become a mighty river that has touched countless lives.",
  },
  {
    id: "sc-h-3",
    group: "school",
    level: "hard",
    title: "The Hidden Library",
    kind: "story",
    text: "Deep inside the old school building, nobody remembered the small room behind the staircase. Priya discovered it by accident one rainy afternoon while searching for shelter. Inside she found shelves packed with books covered in decades of dust. She began visiting every day, reading stories that had waited patiently for a curious mind. The forgotten library soon became her favorite place in the whole world.",
  },
  {
    id: "sc-h-4",
    group: "school",
    level: "hard",
    title: "The Season of Kites",
    kind: "story",
    text: "Every winter, the blue sky above our town fills with bright paper kites. Children climb onto rooftops, holding tight to colorful strings that dance in the cool breeze. Families share sweets and warm snacks as music plays from every corner. The biggest thrill comes from friendly battles where kites try to cut each other's lines. When evening falls, the sky slowly empties, leaving behind a joy that lingers for days.",
  },
  {
    id: "sc-h-5",
    group: "school",
    level: "hard",
    title: "The Tree That Gave Shelter",
    kind: "story",
    text: "An enormous banyan tree stood at the edge of our village for more than a hundred years. Travelers rested under its wide branches during the hottest part of the day. Birds built their nests high among its leaves, and squirrels raced along its twisted roots. Storytellers gathered children there every evening to share tales of kings and heroes. That gentle tree was not just wood and leaves; it was the living heart of our community.",
  },

  // ─────────── HIGH SCHOOL · EASY ───────────
  {
    id: "hs-e-1",
    group: "highschool",
    level: "easy",
    title: "The Power of Books",
    kind: "story",
    text: "Books are silent teachers that open doors to countless worlds. They offer wisdom from people we may never meet and places we may never visit. Reading daily sharpens the mind and widens our understanding of life.",
  },
  {
    id: "hs-e-2",
    group: "highschool",
    level: "easy",
    title: "Why Kindness Matters",
    kind: "story",
    text: "A small act of kindness often travels further than we realize. A smile can ease the worry on a stranger's face, and a patient word can calm a heated room. Kindness does not require money or fame; it only asks that we notice the people around us. Over time, these small choices shape the kind of person we become.",
  },
  {
    id: "hs-e-3",
    group: "highschool",
    level: "easy",
    title: "The Habit of Reading",
    kind: "story",
    text: "Reading every day is one of the simplest ways to grow a sharper mind. Even fifteen focused minutes can introduce new ideas and stronger vocabulary. Books allow us to travel through time and meet thinkers from every culture. Unlike short videos, reading demands our full attention and rewards it richly.",
  },
  {
    id: "hs-e-4",
    group: "highschool",
    level: "easy",
    title: "Healthy Routines",
    kind: "story",
    text: "Most days feel easier when they begin with a steady routine. Waking at a regular time trains the body to feel alert without caffeine. A light meal, a short walk, and a moment of planning set the tone for everything that follows. Discipline, more than motivation, is what keeps our routines alive.",
  },
  {
    id: "hs-e-5",
    group: "highschool",
    level: "easy",
    title: "Learning From Mistakes",
    kind: "story",
    text: "Nobody reaches any meaningful goal without making mistakes along the way. What matters is whether we treat each mistake as proof of failure or as information for improvement. The students who grow fastest are usually the ones who ask the most questions after getting an answer wrong. In time, mistakes become one of our best teachers.",
  },

  // ─────────── HIGH SCHOOL · MEDIUM ───────────
  {
    id: "hs-m-1",
    group: "highschool",
    level: "medium",
    title: "The Courage of Curiosity",
    kind: "story",
    text: "Great discoveries rarely begin with certainty. They begin with a simple question asked by someone brave enough to doubt the obvious. Curiosity pushes us to explore unfamiliar ideas, and in doing so, it shapes both science and society.",
  },
  {
    id: "hs-m-2",
    group: "highschool",
    level: "medium",
    title: "The Weight of Words",
    kind: "story",
    text: "Words carry far more power than most people realize when they speak in haste. A single unkind sentence can stay in someone's mind for years, shaping how they see themselves. A thoughtful compliment can give a struggling person the courage to try again. Because words travel quickly and cannot be pulled back, a little care before speaking saves a great deal of repair afterward.",
  },
  {
    id: "hs-m-3",
    group: "highschool",
    level: "medium",
    title: "The Art of Listening",
    kind: "story",
    text: "Most conversations suffer from the same quiet problem: we listen only long enough to prepare our reply. True listening focuses entirely on understanding rather than responding. When someone feels genuinely heard, they relax, think more clearly, and offer their best ideas. Asking one careful question is often more powerful than sharing ten opinions.",
  },
  {
    id: "hs-m-4",
    group: "highschool",
    level: "medium",
    title: "The Value of Failure",
    kind: "story",
    text: "Failure is rarely as permanent as it feels in the moment. A missed deadline, a poor grade, or a rejected application can feel like the end of something important. With distance, however, most failures turn into quiet redirection toward something better. Failing at a task does not mean being a failure, and remembering that difference is the first step toward progress.",
  },
  {
    id: "hs-m-5",
    group: "highschool",
    level: "medium",
    title: "Why Time Is Precious",
    kind: "story",
    text: "Unlike money, time can never be earned back once it is spent. A busy schedule can create the illusion that we are in control, but often we are simply reacting to the nearest demand. Protecting a few quiet hours each week for reading and deep thinking is one of the most valuable habits anyone can build. Over many years, those choices add up to a meaningful life.",
  },

  // ─────────── HIGH SCHOOL · HARD ───────────
  {
    id: "hs-h-1",
    group: "highschool",
    level: "hard",
    title: "Patience and Persistence",
    kind: "story",
    text: "Achievement is not a single extraordinary moment but a patient accumulation of ordinary efforts. Every skilled craftsman, every celebrated scientist, and every accomplished athlete once stood at the beginning, confused and clumsy. Persistence transforms awkward attempts into graceful mastery over time.",
  },
  {
    id: "hs-h-2",
    group: "highschool",
    level: "hard",
    title: "The Quiet Strength of Habits",
    kind: "story",
    text: "The lives of great achievers rarely look exciting up close. Their days are filled with patient repetition, careful review, and honest self-examination. A single outstanding performance is usually built on thousands of small sessions nobody ever witnessed. True success is less about bursts of inspiration and more about the steady rhythm of daily work.",
  },
  {
    id: "hs-h-3",
    group: "highschool",
    level: "hard",
    title: "Finding Your Own Voice",
    kind: "story",
    text: "Growing up means slowly learning which opinions are genuinely yours and which you have simply inherited. At first it is easier to repeat what teachers, parents, or popular trends suggest. With time, reading widely and thinking carefully helps you test those ideas against experience. A personal voice may be quieter at first, but it grows stronger with every thoughtful conversation.",
  },
  {
    id: "hs-h-4",
    group: "highschool",
    level: "hard",
    title: "The Climate We Share",
    kind: "story",
    text: "The climate we share does not notice national borders or political speeches. Every car, factory, and forest cleared for farmland leaves a trace in the same common atmosphere. Rising temperatures are already reshaping agriculture, health, and migration across the world. The real question is not whether action is necessary, but how quickly we are willing to take it together.",
  },
  {
    id: "hs-h-5",
    group: "highschool",
    level: "hard",
    title: "The Purpose of Education",
    kind: "story",
    text: "Education, at its best, is far more than preparation for a single career. It trains the mind to weigh evidence, the heart to consider others, and the spirit to remain curious throughout life. When learning becomes purely transactional, students graduate with credentials but without the habits that make knowledge useful. A thoughtful education shapes how you vote, how you parent, and how you treat the person behind the counter.",
  },

  // ─────────── COLLEGE · EASY ───────────
  {
    id: "co-e-1",
    group: "college",
    level: "easy",
    title: "Why Learning Never Ends",
    kind: "story",
    text: "Education does not conclude with a degree certificate. The habits you build during your studies determine whether you continue growing for the next fifty years. Curiosity, discipline, and humility remain useful long after the final examination is over.",
  },
  {
    id: "co-e-2",
    group: "college",
    level: "easy",
    title: "The Discipline of Focus",
    kind: "story",
    text: "Focus has quietly become one of the rarest resources in modern life. Notifications, feeds, and endless tabs compete for attention during every working hour. The students who protect a few hours of uninterrupted work each day outperform peers who are technically working longer. Treating attention as a scarce asset is one of the most practical skills college can teach.",
  },
  {
    id: "co-e-3",
    group: "college",
    level: "easy",
    title: "Choosing Your Circle",
    kind: "story",
    text: "The company we keep shapes us in ways we rarely notice at the time. Friends who read widely, pursue goals, and speak honestly lift us toward our better selves. A circle built around gossip or constant complaint slowly narrows our ambitions. A good circle challenges you without mocking you, and it encourages growth without demanding conformity.",
  },
  {
    id: "co-e-4",
    group: "college",
    level: "easy",
    title: "The Cost of Comfort",
    kind: "story",
    text: "Comfort is pleasant in the short term, but it quietly carries a long-term price. Skills grow only when we place ourselves in situations slightly beyond our current ability. Avoiding every hard conversation or challenging subject leaves us underprepared for the real world. College is one of the few places designed to help you practice this lesson safely.",
  },
  {
    id: "co-e-5",
    group: "college",
    level: "easy",
    title: "The Value of Mentorship",
    kind: "story",
    text: "A good mentor can save you years of avoidable mistakes. By sharing their own wrong turns, they offer lessons no textbook could deliver with the same weight. Mentorship is not about being told what to think, but about seeing how an experienced person approaches difficult decisions. Over time, a small network of trusted mentors becomes one of your most valuable professional assets.",
  },

  // ─────────── COLLEGE · MEDIUM ───────────
  {
    id: "co-m-1",
    group: "college",
    level: "medium",
    title: "Ideas Worth Defending",
    kind: "story",
    text: "A well-formed opinion requires more than confidence; it requires evidence, reasoning, and the willingness to revise. The world rewards people who can argue their views clearly while remaining open to the views of others. Articulate thinkers earn trust, while loud thinkers earn only attention.",
  },
  {
    id: "co-m-2",
    group: "college",
    level: "medium",
    title: "The Problem with Shortcuts",
    kind: "story",
    text: "Shortcuts are tempting because they promise the same destination with less effort. In skills like writing, coding, or public speaking, the effort itself is where the real learning happens. Skipping the hard parts leaves a weak foundation that shows up later under pressure. The long way, eventually, turns out to be the only reliable route to mastery.",
  },
  {
    id: "co-m-3",
    group: "college",
    level: "medium",
    title: "Reading Beyond Your Field",
    kind: "story",
    text: "A student who reads only within their major graduates with a narrow lens. Ideas rarely move forward within a single discipline; they borrow, collide, and recombine across subjects. A physicist who reads history, or an economist who studies psychology, gains tools most of their peers never see. In an age of specialization, wide reading quietly remains one of the most powerful forms of learning.",
  },
  {
    id: "co-m-4",
    group: "college",
    level: "medium",
    title: "The Practice of Writing Clearly",
    kind: "story",
    text: "Clear writing is thinking made visible to others. If a paragraph feels tangled on the page, it is almost always tangled in the mind that produced it. Revising a sentence to be simpler forces us to understand our own argument more precisely. The ability to explain something clearly is never a side skill; it is usually the main skill.",
  },
  {
    id: "co-m-5",
    group: "college",
    level: "medium",
    title: "Why Ethics Still Matters",
    kind: "story",
    text: "Technical skill without ethical judgment is a dangerous combination in any profession. A talented engineer, lawyer, or doctor can quietly cause great harm when ambition runs ahead of conscience. Asking whether an action is right, not only legal or profitable, is the habit that shapes a trusted career. Great institutions are built by people willing to ask such questions long before anyone else does.",
  },

  // ─────────── COLLEGE · HARD ───────────
  {
    id: "co-h-1",
    group: "college",
    level: "hard",
    title: "The Architecture of Habits",
    kind: "story",
    text: "Consistency, not intensity, is the true architect of excellence. The spectacular sprint impresses onlookers for a day, but the steady jog transforms a life over a decade. By designing an environment that favors your intended habits, you remove the daily dependence on willpower and replace it with structure, rhythm, and momentum.",
  },
  {
    id: "co-h-2",
    group: "college",
    level: "hard",
    title: "On the Temptation of Certainty",
    kind: "story",
    text: "Certainty is emotionally satisfying because it relieves the discomfort of not knowing. Yet in most fields, honest thinkers live comfortably with uncertainty and revise their views as evidence changes. Loud confidence is often mistaken for competence, but the strongest minds tend to speak with careful qualifications. Wisdom, in the end, is less about having answers and more about asking sharper questions.",
  },
  {
    id: "co-h-3",
    group: "college",
    level: "hard",
    title: "The Long Game of Reputation",
    kind: "story",
    text: "A reputation is built slowly over years and lost in a matter of minutes. Each small choice, whether to meet a deadline, return a message, or credit another's work, quietly adds to the account. Employers and colleagues talk to each other far more than students realize, and a pattern of reliability travels quickly. The graduates who flourish longest are usually the ones who treated every early assignment with full seriousness.",
  },
  {
    id: "co-h-4",
    group: "college",
    level: "hard",
    title: "Thinking in Systems",
    kind: "story",
    text: "Most complex problems, from traffic to climate, arise from systems rather than from single causes. A student trained only to find the one responsible party will miss the feedback loops, delays, and incentives that actually drive outcomes. Thinking in systems means tracing how a change in one corner ripples through many others, often in unexpected ways. This discipline produces more humble conclusions and more durable solutions.",
  },
  {
    id: "co-h-5",
    group: "college",
    level: "hard",
    title: "The Responsibility of Privilege",
    kind: "story",
    text: "Every generation inherits opportunities that earlier generations struggled to create. Recognizing that inheritance is not a source of guilt but a call to stewardship. The most admirable professionals use their training to open doors for those still standing outside. A meaningful life is rarely built on how much we accumulate; it is built on how generously we pass our good fortune along.",
  },

  // ─────────── PROFESSIONAL · EASY ───────────
  {
    id: "pr-e-1",
    group: "professional",
    level: "easy",
    title: "Self Introduction",
    kind: "communication",
    text: "Hello, my name is Alex and I am glad to meet you today. I work as a software engineer with an interest in building thoughtful products. Outside of work, I enjoy reading, walking, and learning new languages.",
  },
  {
    id: "pr-e-2",
    group: "professional",
    level: "easy",
    title: "Greeting a New Team",
    kind: "communication",
    text: "Hello everyone, I am very happy to be joining the team this week. I have spent the last three years working on customer-facing products, and I am eager to learn how things are done here. Please feel free to share any advice or context that would help me get up to speed. Thank you for making me feel welcome already.",
  },
  {
    id: "pr-e-3",
    group: "professional",
    level: "easy",
    title: "Asking for Help",
    kind: "communication",
    text: "I have a quick question if you have a moment this afternoon. I have been working on the report we discussed yesterday, and I am running into a small blocker around the data source. Rather than lose another day on it, I thought it would be more efficient to bring it to you directly. Thank you for considering the time.",
  },
  {
    id: "pr-e-4",
    group: "professional",
    level: "easy",
    title: "Declining Politely",
    kind: "communication",
    text: "Thank you so much for thinking of me for this opportunity. I have had time to review the details, and I do not think I can give it the attention it deserves over the next few weeks. I would be glad to help again once things settle, and I hope you find someone who can step in this time. I really appreciate your understanding.",
  },
  {
    id: "pr-e-5",
    group: "professional",
    level: "easy",
    title: "Thanking a Colleague",
    kind: "communication",
    text: "I wanted to take a moment to thank you for your help on yesterday's presentation. Your feedback on the structure made the whole argument land more clearly with the client. It means a great deal to have colleagues who care about the work as much as you do. Please let me know when I can return the favor.",
  },

  // ─────────── PROFESSIONAL · MEDIUM ───────────
  {
    id: "pr-m-1",
    group: "professional",
    level: "medium",
    title: "Giving a Status Update",
    kind: "communication",
    text: "Thank you for making time for this update. Since last week, we have shipped the authentication flow, resolved two critical bugs, and begun work on the reporting module. Our primary risk this week is the delay in design handoff, and I would appreciate your help unblocking it.",
  },
  {
    id: "pr-m-2",
    group: "professional",
    level: "medium",
    title: "Leading a Short Meeting",
    kind: "communication",
    text: "Thank you all for being on time this morning. We have three items to cover in the next twenty minutes, and I will keep us moving so we can finish on schedule. First, a quick update on the launch plan, then a short discussion about the support backlog, and finally the decision on next quarter's hiring. Let us get started with the launch update.",
  },
  {
    id: "pr-m-3",
    group: "professional",
    level: "medium",
    title: "Handling a Disagreement",
    kind: "communication",
    text: "I appreciate you sharing your view so directly, and I want to make sure I understand it before responding. From what I heard, you are concerned about the timeline and the risk to customers if we ship before the integration tests are complete. I share that concern, although I am weighing it against the cost of further delay. Could we take thirty minutes this afternoon to look at the data together before deciding?",
  },
  {
    id: "pr-m-4",
    group: "professional",
    level: "medium",
    title: "Introducing Yourself in an Interview",
    kind: "communication",
    text: "Thank you for inviting me to speak with you today. I have spent the last five years working on data products, most recently leading a team that rebuilt our internal analytics platform. What draws me to this role is the combination of scale and clarity of mission that your team is known for. I am looking forward to learning more about where you are headed over the next few years.",
  },
  {
    id: "pr-m-5",
    group: "professional",
    level: "medium",
    title: "Delivering Difficult Feedback",
    kind: "communication",
    text: "Thank you for making time for this conversation; I know these sessions are rarely easy. I have been noticing a pattern in the last few projects that I want to address with you directly. Deadlines have been missed more often than we agreed, and the team has had to pick up work at short notice. I am not questioning your ability, which is clear, but I think we need a better system for tracking your commitments.",
  },

  // ─────────── PROFESSIONAL · HARD ───────────
  {
    id: "pr-h-1",
    group: "professional",
    level: "hard",
    title: "Owning a Mistake Gracefully",
    kind: "communication",
    text: "I want to take a moment to acknowledge an error in the proposal I shared on Tuesday. The revenue projection on slide four relied on outdated data, and the corrected figure is meaningfully lower. I have attached a revised version with the accurate numbers, an explanation of what changed, and the safeguards we are putting in place to prevent a similar oversight.",
  },
  {
    id: "pr-h-2",
    group: "professional",
    level: "hard",
    title: "Negotiating a Project Timeline",
    kind: "communication",
    text: "I want to walk you through our team's assessment of the proposed launch date before we commit to it publicly. After a careful review of the open work items and the dependencies we do not yet control, I believe the original target presents significant risk to both quality and morale. I am proposing a revised timeline that adds two weeks for integration testing and a short buffer for unexpected issues. I am open to your questions and to any constraints I may be missing from the broader business picture.",
  },
  {
    id: "pr-h-3",
    group: "professional",
    level: "hard",
    title: "Communicating During a Crisis",
    kind: "communication",
    text: "Thank you for your patience while we gather the facts on this incident. At approximately ten this morning, a configuration change caused a partial outage affecting a portion of our customers. Our engineering team identified the root cause within twenty minutes and has since restored full service. I will share a written post-incident review within forty-eight hours, including the specific changes we are making to prevent a recurrence.",
  },
  {
    id: "pr-h-4",
    group: "professional",
    level: "hard",
    title: "Declining an Executive Request",
    kind: "communication",
    text: "I have given careful thought to your proposal, and I want to be candid with you about where I have landed. While I understand the strategic reasoning, I believe committing our team to this initiative this quarter would meaningfully weaken delivery on the commitments we have already made. Rather than overcommit and then renegotiate mid-quarter, I would prefer to discuss what we could realistically take on in the following cycle. I am confident we can find a path that serves the broader strategy without putting our current commitments at risk.",
  },
  {
    id: "pr-h-5",
    group: "professional",
    level: "hard",
    title: "Presenting a Proposal to Leadership",
    kind: "communication",
    text: "Thank you for the time on your calendars today; I know everyone in this room is managing a full agenda. I am here to propose that we invest in a dedicated reliability team during the next two quarters, and I will support that recommendation with three sets of evidence. First, customer-facing incident data from the past year. Second, the engineering hours currently being lost to reactive work. Finally, a comparison with peer companies who made a similar investment and the outcomes they observed.",
  },
];

export function pickParagraph(
  group: AgeGroup,
  level: Difficulty,
  excludeId?: string
): Paragraph | null {
  const matches = PARAGRAPHS.filter((p) => p.group === group && p.level === level);
  if (matches.length === 0) return null;
  const pool = excludeId ? matches.filter((p) => p.id !== excludeId) : matches;
  const candidates = pool.length > 0 ? pool : matches;
  return candidates[Math.floor(Math.random() * candidates.length)];
}
